name: CI del bot de Minecraft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Construir con Gradle
      run: ./gradlew build
    - name: Ejecutar el bot de Minecraft
      run: java -jar build/libs/minecraft-bot.jar
